### PR TITLE
Add indent line support.

### PR DESCRIPTION
**Pull request by lu5je0**
image

### CODE REVIEW

**Comment by lambdalisue** [comment]
It seems cool but commits are bit messy. Could you reorganize those?

**Comment by lu5je0** [comment]
I've squashed the commits, and should i squash them into one commit?

**Comment by lambdalisue** [comment]
You don't need to squash to one commit but please re-organize those logically.

**Comment by lu5je0** [comment]
ok，I have reorganized it.

**Comment by lambdalisue** [comment]
I'm sorry but I don't think "Fix typo" is an organized commit and it seems what you did in that commit is not only fixing typos...

**Comment by lambdalisue** [comment]
Closed by #20 Thanks for your contribution 👍

**Pull request closed without merging**
